import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Baloo_2 } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';

const clashDisplay = localFont({
  src: '../fonts/ClashDisplay-Variable.ttf',
  variable: '--font-clash',
  display: 'swap',
  weight: '200 300 400 500 600 700',
});

const baloo = Baloo_2({
  variable: '--font-baloo',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
});

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.variable} ${baloo.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
